### PR TITLE
Moved to actions, added badge

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by evaherrada** [comment]
@ladyada Yeah, I'm not entirely sure what's going on here and why it's failing. I can take another look in a bit.

**Comment by ladyada** [comment]
ditto, its some header rearrangement thats causing problems

**Comment by evaherrada** [comment]
Same here, what with the doxygen failing

**Comment by ladyada** [comment]
remove the doxygen check, we dont care about doxying this library

**Comment by evaherrada** [comment]
Will do

**Pull request merged**
